[project]
name = "test1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kmansilla", email = "mansilla.katia@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
test1 = "test1:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
